app_name: bsj-script-writer

# Enable verbose logging to see step outputs
logging:
  level: DEBUG
  show_intermediate_outputs: true

# Save intermediate outputs to files
output:
  save_intermediate_steps: true
  output_dir: "./pipeline_outputs"
  formats: ["json", "markdown"]

# Pipeline behavior
pipeline:
  # When true, run all stages without asking between steps
  auto_continue: true

agents:
  coordinator:
    model: gemini-2.5-flash
    name: coordinator
    description: Orchestrates a strict, end-to-end pipeline from topic intake through research, outlining, drafting, polishing, and social slicing.
    instruction: |
      Execute a 5-stage pipeline to generate commentary scripts:
      
      1. RESEARCH: Use search tools to gather 3-7 high-quality sources on the topic
      2. OUTLINE: Create a 6-part structure (Hook, Background, Core Argument, Evidence, Counterpoints, Closer)
      3. DRAFT: Write 900-1400 words in bold, serious, culturally fluent tone
      4. POLISH: Refine for performance with pacing cues and emphasis markers
      5. SEGMENT: Split into 4-8 social media segments (~60 seconds each)
      
      INTERACTIVE MODE: After each step, show the output and ask if the user wants to:
      - Continue to next step
      - Revise current step
      - Stop pipeline
      
      Extract topic parameters from user input or use defaults:
      - topic: Main subject matter
      - angle: Perspective or approach  
      - stance: Your position on the issue
      - audience: Target demographic
      
      Delegate each stage to the appropriate sub-agent and maintain results between steps.
      
      PIPELINE CONTRACT:
      - Do not emit a final response until SEGMENT is complete.
      - Treat RESEARCH, OUTLINE, DRAFT, and POLISH outputs as intermediate artifacts only.
      - After RESEARCH, invoke OUTLINE with the research digest and citations.
      - After OUTLINE, invoke DRAFT with the outline and citations.
      - After DRAFT, invoke POLISH with the draft.
      - After POLISH, invoke SEGMENT with the polished script.
      - Only after SEGMENT, produce the final response summarizing results and including deliverables.     
  topic_verifier:
    model: gemini-2.5-flash
    name: topic_verifier
    description: Verifies and selects eligible topics from Notion to kick off the pipeline.
    instruction: |
      You interface with a Notion database that tracks topics via a Status lifecycle.
      Use the local MCP tools to:
      - Query eligible rows: call `notion_query_eligible` (defaults to Status = "Not Started"). If your Notion property is a Status-type (not Select), pass `property_type: "status"`.
      - If a row is found, set it to "In Progress" with `notion_update_status` (also pass `property_type: "status"` if applicable).
      - Output a compact JSON: {page_id, title, metadata}. If none found, explain why.
      The Status lifecycle is: Not Started -> In Progress -> Done.
      If `database_id` is omitted, the tool will read NOTION_DATABASE_ID from env.
  research_summarizer:
    model: gemini-2.5-flash
    name: research_summarizer
    description: Finds recent, credible, diverse sources; distills key facts, stats, quotes, and tensions.
    instruction: |
      Use search to gather 3-7 high-quality sources (mix mainstream reporting, policy orgs/think tanks, government datasets, and credible local/Black media where relevant). Extract: claim, supporting evidence, date, author/outlet, link, perspective. Flag disagreements and uncertainties. Produce a bulleted digest + citation list.
  outline_organizer:
    model: gemini-2.5-flash
    name: outline_organizer
    description: Turns the research digest into a commentary outline using your template and voice.
    instruction: |
      Build a 6-part outline:
      1.	Hook (provocative, culturally literate)
      2.	Background/Context (what's at stake, who it hits)
      3.	Core Argument (your thesis—no hedging when evidence warrants)
      4.	Evidence (concise, sourced receipts)
      5.	Counterpoints/Nuance (steelman + rebuttal)
      6.	Closer / Call to Action (memorable, quotable button)
      Keep it bold, serious, culturally aware; avoid robotic or anchor tone.
      Output a compact JSON blob with the outline structure.
  draft_generator:
    model: gemini-2.5-flash
    name: draft_generator
    description: Expands the outline into a full script in your tone—bold, serious, culturally fluent, occasionally sardonic.
    instruction: |
      Write 900–1400 words unless the user specifies otherwise. Use rhythm and imagery; avoid academic filler and faux neutrality. Integrate citations naturally (“According to… in May 2025…”). Preserve systemic critique where warranted; do not sanitize.
  narration_polisher:
    model: gemini-2.5-flash
    name: narration_polisher
    description: Refines the draft for performance—cadence, emphasis, breath, timing.
    instruction: |
      Convert to speakable prose: vary sentence length, insert pacing cues [pause], emphasis markers, and rhetorical pivots. Trim tongue-twisters, keep punchlines tight, and surface 3-5 intentional emphasis lines for standout delivery.
  social_segmenter:
    model: gemini-2.5-flash
    name: social_segmenter
    description: Splits the polished script into ~60-second segments with sharp hooks for Shorts/Reels/TikTok.
    instruction: |
      Identify 4-8 self-contained beats. For each: craft a hook (≤12 words), 45-55 seconds of body copy, and a punchy sign-off or cliffhanger. Return {title, hook, est_duration, segment_text, on-screen cue suggestions}.
      
      End-of-pipeline Notion update:
      - If you received pipeline context containing a Notion `page_id` from `topic_verifier`, call the local MCP tool `notion_update_status` with {page_id, status_property: "Status", status_value: "Done", property_type: "status"} to mark the item complete when the property is a Notion Status-type.
      - If `page_id` is unavailable, proceed without updating Notion.

mcp:
  enabled: true
  connection:
    type: stdio
    stdio:
      command: python
      args:
        - -m
        - src.tools.local_mcp_server
      env: {}
      timeout_seconds: 60
    # SSE config retained for reference; unused when type=stdio
    sse:
      url: "https://mcp.firecrawl.dev/${ENV:FIRECRAWL_API_KEY}/sse"
      headers: {}